//Конфигурации, касающиеся только корневого проекта (в нашем примере нет)
plugins {
    id 'org.springframework.boot' version '3.5.6' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}
//Конфигурации, касающиеся всех модулей, включая корневой
allprojects {
    group = 'ru.project'
    version = '0.0.1-SNAPSHOT'
    repositories {
        mavenCentral() // Указываем репозиторий для зависимостей
    }
}

//Конфигурации дочерних модулей. К корневому не применяются
subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        implementation'org.mapstruct:mapstruct:1.6.3'
        annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
        annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
    }

    tasks.named("test") {
        useJUnitPlatform()
    }
}