services:

  postgres:
    image: postgres:16.1
    container_name: market
    restart: always
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
    volumes:
      - market:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  market: