spring:
  application:
    name: market

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org:
      zalando:
        logbook: INFO
    org.springframework: INFO
    org.hibernate: INFO
    ru.yandex.practicum.market: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO
    liquibase: INFO
