server:
  port: 8081

spring:

  application:
    name: payment

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


logging:
  level:
    root: debug
    org:
      zalando:
        logbook: debug
    org.springframework: debug
    ru.yandex.practicum.market: debug
    org.springframework.boot.autoconfigure.liquibase: info
    liquibase: info
