spring:
  application:
    name: market

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: debug
    org:
      zalando:
        logbook: debug
    org.springframework: debug
    ru.yandex.practicum.market: debug
    org.springframework.boot.autoconfigure.liquibase: info
    liquibase: info
